name: pepMeld
channels:
  - conda-forge
dependencies:
  # required
  - numpy>=1.15
  - python>=3.2
  - pandas>=17.1
  - seaborn>=0.7.0
  - sklearn>=0.19
  - matplotlib>=3.1.0
  - statsmodels>=0.8.0
  - tests
  - pytests